#!/bin/bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

TARGET="/home/a1mirr/kektura_app"
GIT_DIR="/home/a1mirr/kektura.git"

mkdir -p $TARGET
git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f main

cd $TARGET
echo "Installing dependencies..."
npm ci || npm install

echo "Building Next.js app..."
npm run build

echo "Restarting PM2..."
pm2 reload kektura || pm2 start npm --name "kektura" -- start
