// Spec 0004 AC-9: a seed generated by scripts/build-data.mjs removes the rows the new source no longer has and
// moves users' stamps first. Runs against the real local database (`npm run testdb:start`) and skips itself when
// it isn't running; CI's end-to-end job runs it. Every drill is one transaction that is rolled back, so the
// reference data other tests read is never changed.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import { describe, expect, it } from "vitest";

const read = (file: string) => fs.readFileSync(new URL(`../supabase/${file}`, import.meta.url), "utf8");
const seed = read("seed.sql");
const seedExtra = read("seed_extra.sql");

// Runs a script in one psql session; throws on the first error.
function run(sql: string): string[] {
  return execFileSync("docker", ["exec", "-i", "supabase_db_kektura", "psql", "-U", "postgres", "-At", "-v", "ON_ERROR_STOP=1", "-q"], {
    input: sql,
    encoding: "utf8",
  })
    .trim()
    .split("\n");
}

const hasDatabase = () => {
  try {
    return run("select 1;")[0] === "1";
  } catch {
    return false;
  }
};

const USER = "00000000-0000-4000-8000-0000000000d1";
const createUser = `insert into auth.users (id, instance_id, aud, role, email, raw_user_meta_data) values ('${USER}', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'seed-drill@kektura.test', '{}');`;

// The seed's own transaction is inside the drill's: its begin and commit are commented out, the drill rolls back.
const inner = (text: string) => text.replace(/^begin;$/m, "-- begin").replace(/commit;\s*$/, "-- commit");

describe("spec 0004: seeds that clean up after themselves", () => {
  it("AC-9: each seed file is one transaction", () => {
    for (const text of [seed, seedExtra]) {
      expect(text).toMatch(/^begin;$/m);
      expect(text.trimEnd()).toMatch(/commit;$/);
    }
  });

  it("AC-9: a stamp on a code the new seed dropped moves to the remaining variant of the place, and the old row goes", (ctx) => {
    if (!hasDatabase()) return ctx.skip();
    const without = seed
      .split("\n")
      .filter((line) => !(line.startsWith("  (") && line.includes("'OKTPH_03_1'")))
      .join("\n")
      .replace("'OKTPH_03_1', ", "");
    expect(without).not.toContain("'OKTPH_03_1'");
    const lines = run(
      [
        "begin;",
        createUser,
        `insert into public.user_stamps (user_id, checkpoint_id, stamped_on) select '${USER}', id, '2026-09-30' from public.checkpoints where code = 'OKTPH_03_1';`,
        inner(without),
        `select 'stamps:' || string_agg(c.code || '@' || s.stamped_on, ',') from public.user_stamps s join public.checkpoints c on c.id = s.checkpoint_id where s.user_id = '${USER}';`,
        "select 'left:' || count(*) from public.checkpoints where code = 'OKTPH_03_1';",
        "rollback;",
      ].join("\n"),
    );
    expect(lines).toContain("stamps:OKTPH_03_2@2026-09-30"); // the stamp and its date moved
    expect(lines).toContain("left:0");
  });

  it("AC-9: an extra stamp that came back under a new code keeps its users' stamps (same name)", (ctx) => {
    if (!hasDatabase()) return ctx.skip();
    const oldCode = "47.3509,16.4786:Velem (Szombathelyi egyházmegye - Velem)";
    const newCode = "47.3509,16.4787:Velem (Szombathelyi egyházmegye - Velem)";
    expect(seedExtra).toContain(`'${oldCode}'`);
    const moved = seedExtra.split(`'${oldCode}'`).join(`'${newCode}'`);
    const lines = run(
      [
        "begin;",
        createUser,
        `insert into public.user_extra_stamps (user_id, extra_id, stamped_on) select '${USER}', id, '2026-09-30' from public.extra_stamps where code = '${oldCode}';`,
        inner(moved),
        `select 'stamps:' || string_agg(e.code || '@' || s.stamped_on, ',') from public.user_extra_stamps s join public.extra_stamps e on e.id = s.extra_id where s.user_id = '${USER}';`,
        `select 'left:' || count(*) from public.extra_stamps where code = '${oldCode}';`,
        "rollback;",
      ].join("\n"),
    );
    expect(lines).toContain(`stamps:${newCode}@2026-09-30`);
    expect(lines).toContain("left:0");
  });

  it("AC-9: a place that is gone entirely takes its stamps with it, and a placeholder row without a code goes", (ctx) => {
    if (!hasDatabase()) return ctx.skip();
    const lines = run(
      [
        "begin;",
        createUser,
        // a placeholder row (code null) with a stamp on it, and a place the seed does not know
        "insert into public.checkpoints (seq, code, place_key, stage, stage_seq, name, lat, lng, km_from_start) values (9001, null, 'GONE_PLACE', 1, 99, 'Gone', 47, 17, 0), (9002, 'GONE_PLACE_1', 'GONE_PLACE_X', 1, 98, 'Gone too', 47, 17, 0);",
        `insert into public.user_stamps (user_id, checkpoint_id) select '${USER}', id from public.checkpoints where seq in (9001, 9002);`,
        inner(seed),
        `select 'stamps:' || count(*) from public.user_stamps where user_id = '${USER}';`,
        "select 'rows:' || count(*) from public.checkpoints where seq in (9001, 9002);",
        "select 'total:' || count(*) from public.checkpoints;",
        "rollback;",
      ].join("\n"),
    );
    expect(lines).toContain("stamps:0");
    expect(lines).toContain("rows:0");
    expect(lines).toContain("total:220");
  });
});
